#!/bin/bash

export FROM="quay.io/fedora/fedora-coreos-bls-cocl:42.20250901.3.0"
export TAG="quay.io/fedora/fedora-coreos-uki-cocl:42.20250901.3.0"
# export FROM="quay.io/fedora/fedora-coreos-bls-cocl:42.20250901.3.1"
# export TAG="quay.io/fedora/fedora-coreos-uki-cocl:42.20250901.3.1"
exec ./build-bootc-uki
