---

# tmt-reboot and reboot do not work in this case
# reboot in ansible is the only way to reboot in tmt prepare
- name: Reboot after system-reinstall-bootc
  hosts: all
  tasks:
    - name: Reboot system to image mode
      reboot:

    - name: Wait for connection to become reachable/usable
      wait_for_connection:
        delay: 30
