name: Rust

permissions:
  actions: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: quay.io/coreos-assembler/fcos-buildroot:testing-devel

    steps:
    - name: Install skopeo
      run: yum -y install skopeo
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt -- --check -l
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

